### ISSUE TITLE
USER STORY:<User account>

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/Book-review-p4#2]
As a **User**, I would like **create a account at this page **, so that **save my favourite books and find my prefereed one's.**

### Acceptance Criteria
-	Acceptance Criteria 1: the user account should get user email information,full name and password 
-	Acceptance Criteria 2:it should check the password, save it , after the submit button
-	Acceptance Criteria 3: After submitting the default submission confirmation should be adjusted to include the user name. 

### Tasks
-	[] Task 1 – fit the view for the phone, desktop and design(HTML;CSS)
-	[] Task 2 – create a field where it will be displayed the name of the user
-	[] Task 3 – create a save the information field
-	[] Task 4 – test the functionality

### Epic: #4
