### ISSUE TITLE
USER STORY:<Review board display of the top 5>

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/Book-review-p4#3]
As a **administrator **, I would like **a board that features the most popular books **, so that **show the user the most promising and interestinng books **

### Acceptance Criteria
-	Acceptance Criteria 1:should be displayed in a different window and linked to the main page
-      Acceptance Criteria2:the windoe should the display the top 5 book`s of the month
-      Acceptance Criteria3:the window closes and returns on the main page

### Tasks
-	[] Task 1 – Develop a link to the poll display or connetion on the main page
-	[] Task 2 – The display should open in a new window and also being able to close
-	[] Task 3 –  The window should adjust depending on the view phone and desktop
-	[] Task 4 –  It should display the top 5 of the best book in that  month
-	[] Task 5 –  Test the functionality of the display

##Itireration:

##Points:

##Epic:
